import os
import telebot

TOKEN = os.environ.get("8452130052:AAEmgL6VpmuGNi6NAX88byrKV7q-QGxyy-o")
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def start(message):
    bot.reply_to(message, "–°–∞–ª–∞–º! –ú–µ–Ω GitHub Actions –∞—Ä–∫—ã–ª—É—É –æ–Ω–ª–∞–π–Ω–º—ã–Ω ü§ñ")

@bot.message_handler(func=lambda m: True)
def echo(message):
    bot.reply_to(message, f"–°–µ–Ω –∂–∞–∑–¥—ã“£: {message.text}")

bot.infinity_polling()
